name: DevSecOps Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sast:
    name: Static Application Security Testing (SAST)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep without failing the job
      run: |
        semgrep --config=p/owasp-top-ten --json --output=semgrep.json || true
        echo "Semgrep scan completed, results saved in semgrep.json"

    - name: Upload Semgrep results
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-results
        path: semgrep.json
